server:
  port: 8080
  serverHeader: collection

spring:
    #应用程序名称
    application:
        name: cityManage
    #引入其他yml
    profiles:
        #受理中心配置
        include: accept-center
    #guava
    cache:
        type: guava
        #有且只有一个cache-name
        cache-name: commonCacheGuava
        guava:
            ##最大缓存数量，失效时间
            spec: maximumSize=1000,expireAfterWrite=60m
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://localhost:3306/poic?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&serverTimezone=UTC
          username: root
          password: mycp1122
#          url: jdbc:mysql://94.191.38.143:3306/cspadmin?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&serverTimezone=UTC
 #         username: root
 #         password: Aa.654321
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20


mybatis:
  mapper-locations: classpath:com/city/management/collection/mapper/base/*.xml,com/city/management/collection/mapper/ext/*.xml
  type-aliases-package: com.city.management.collection.model.base

devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署

logging:
    level:
        com:
            city:
                sonar:
                    dao:
                        ext: debug


management:
    endpoint:
        health:
            show-details: always






